default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: react-checklist_development

test:
  <<: *default
  database: react-checklist_test

production:
  <<: *default
  database: react-checklist_production
  username: api
  password: skyscraper94
